const posiciones = {
  "4ta": [
    {
      pos: 1,
      equipo: "Asociación Española de Neuquén",
      pj: 8,
      g: 6,
      p: 2,
      escudo: "escudos/AEN.png",
    },
    {
      pos: 2,
      equipo: "Club Cipolletti",
      pj: 8,
      g: 5,
      p: 3,
      escudo: "escudos/CAC.png",
    },
    {
      pos: 2,
      equipo: "Club Pelota Paleta Plottier",
      pj: 8,
      g: 5,
      p: 3,
      escudo: "escudos/PPP.png",
    },
    {
      pos: 4,
      equipo: "Club Atlético Regina",
      pj: 8,
      g: 4,
      p: 4,
      escudo: "escudos/CAR.png",
    },

    {
      pos: 5,
      equipo: "Club Atlético Cinco Saltos",
      pj: 8,
      g: 2,
      p: 6,
      escudo: "escudos/CACS.png",
    },
    {
      pos: 5,
      equipo: "Club Unión Alem Progresista",
      pj: 8,
      g: 2,
      p: 6,
      escudo: "escudos/CUAP.png",
    },
  ],
  "3ra": [
    {
      pos: 1,
      equipo: "Club Unión Alem Progresista",
      pj: 8,
      g: 8,
      p: 0,
      escudo: "escudos/CUAP.png",
    },
    {
      pos: 2,
      equipo: "Club Pelota Paleta Plottier",
      pj: 8,
      g: 6,
      p: 2,
      escudo: "escudos/PPP.png",
    },
    {
      pos: 3,
      equipo: "Club Atlético Cinco Saltos",
      pj: 8,
      g: 3,
      p: 5,
      escudo: "escudos/CACS.png",
    },
    {
      pos: 4,
      equipo: "Asociación Española de Neuquén",
      pj: 8,
      g: 4,
      p: 4,
      escudo: "escudos/AEN.png",
    },
    {
      pos: 5,
      equipo: "Club Cipolletti",
      pj: 8,
      g: 2,
      p: 6,
      escudo: "escudos/CAC.png",
    },
    {
      pos: 6,
      equipo: "Club Atlético Regina",
      pj: 8,
      g: 1,
      p: 7,
      escudo: "escudos/CAR.png",
    },
  ],
  "2da": [
    {
      pos: 1,
      equipo: "Club Unión Alem Progresista",
      pj: 8,
      g: 7,
      p: 1,
      escudo: "escudos/CUAP.png",
    },
    {
      pos: 2,
      equipo: "Club Atlético Cinco Saltos",
      pj: 8,
      g: 6,
      p: 2,
      escudo: "escudos/CACS.png",
    },
    {
      pos: 3,
      equipo: "Club Pelota Paleta Plottier",
      pj: 8,
      g: 5,
      p: 3,
      escudo: "escudos/PPP.png",
    },
    {
      pos: 4,
      equipo: "Club Cipolletti",
      pj: 8,
      g: 3,
      p: 5,
      escudo: "escudos/CAC.png",
    },
    {
      pos: 4,
      equipo: "Asociación Española de Neuquén",
      pj: 8,
      g: 3,
      p: 5,
      escudo: "escudos/AEN.png",
    },
    {
      pos: 6,
      equipo: "Club Atlético Regina",
      pj: 8,
      g: 0,
      p: 8,
      escudo: "escudos/CAR.png",
    },
  ],
};
